export const PROFILE_IMAGE_LISTEN = "tour/PROFILE_IMAGE_LISTEN";

export const ABOUT_LISTEN = "tour/ABOUT_LISTEN";

export const DESIGNATION_LISTEN = "tour/DESIGNATION_LISTEN";

export const USER_REGISTER_LISTEN = "tour/USER_REGISTER";
export const USER_REGISTER_SUCCESS = "tour/USER_REGISTER_SUCCESS";