export const LOGIN_LISTEN = "login/LOGIN_LISTEN";
export const LOGIN_SUCCESS = "login/LOGIN__SUCCESS";

export const CHECK_CUR_USER_LISTEN = "login/CHECK_CUR_USER_LISTEN";

export const PROFILE_CREATE_CHECK_LISTEN = "login/PROFILE_CREATE_CHECK_LISTEN";
export const PROFILE_CREATE_CHECK_SUCCESS = "login/PROFILE_CREATE_CHECK_SUCCESS";